require:
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'lib/.rbnext/**/*'
    - 'lib/generators/**/templates/*.rb'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
